# Generated by Django 5.1.3 on 2024-11-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-09-03'),
            preserve_default=False,
        ),
    ]
